### ISSUE TITLE
latest news looks bad when you have images

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/responsive-boat#13]
@rodica-andronache take a look at the boat here : http://wp-themes.com/responsiveboat/#latestnews, is not aligned.

**Comment by rodica-andronache** [comment]
@ineagu aici nu reusesc sa fac. O sa trimit asa, si o sa incerce claudiu sa rezolve cand vine din concediu

**Comment by ineagu** [comment]
Eu as lasa meniul centrat initial, sa se duca in dreapta doar la scroll

**Comment by rodica-andronache** [comment]
@ineagu ok, o sa-l modific maine si trimit din nou
