### ISSUE TITLE
Add an option in Customizer to allow

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/responsive-boat#22]
shortcode from contact form

**Comment by rodica-andronache** [comment]
@ineagu do you think it's a good idea to add an input here where the user can enter a shortcode for a contact form? Because right now I just removed the contact form section and some users are asking for this

**Comment by ineagu** [comment]
It abould be fully compatible with pirate forms, if plugin is activated, the  customizer section should appear
