### ISSUE TITLE
Testimonials background color does not work

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/responsive-boat#37]
This works in Zerif Pro but not Responsive boat. I know child themes dont usually update, but is there a way that only the new users who download the theme get the patch without people using the child theme already seeing any update and losing their changes? @rodica-andronache

**Comment by UVLabs** [comment]
+1

**Comment by UVLabs** [comment]
@rodica-andronache this is being caused by the !important on this line: https://github.com/Codeinwp/responsive-boat/blob/production/style.css#L148

**Comment by mileamadalin** [comment]
@UVLabs @rodica-andronache 

I'm not sure if is a good idea to update the child theme because basically the customers make their changes as well and they will lose all changes. We did that once ... and went bad. I think the best way is to create a doc with this fix and then we can give them the doc.

**Comment by UVLabs** [comment]
@mileamadalin yes I'm aware, was wondering if we could fix it moving forward (without pushing the update to wp.org) and still create a doc to fix it for previous users.

thoughts @rodica-andronache ?

**Comment by rodica-andronache** [comment]
@UVLabs I think that maybe if we add and important tag also in zerif pro, here https://github.com/Codeinwp/zerif-pro/blob/production/functions.php#2316 it would work. But we need to test this better before making the change. So, I'll move this issue to zerif pro, and we'll see there, if we can do anything https://github.com/Codeinwp/zerif-pro/issues/587
