### ISSUE TITLE
Theme loses all transparency when using Zerif Pro template

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/responsive-boat#38]
When RB is using Zerif Lite it has all the transparency and nice features shown from the demo, but as soon as you change the template to zerif pro it loses all the transparency of the buttons and the menu, also the backgrounds of the sections lose it's transparency. @rodica-andronache

**Comment by UVLabs** [comment]
+1

**Comment by rodica-andronache** [comment]
Cristi please investigate if we can do something here from the theme or maybe a solution to use in a doc for ResponsiveBoat

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , not much that I can do here ... we should ask customers to add this code to fix the style when using zerif pro 

`function responsiveboat_background_fix(){
	return array(
		'default-image' => get_stylesheet_directory_uri().'/images/bg.jpg',
		'default-repeat'         => 'no-repeat',
		'default-position-x'     => 'center',
		'default-attachment'     => 'fixed'
	);
}
add_filter('wp_themeisle_custom_background_args','responsiveboat_background_fix');



function responsiveboat_setup_fix() {

	register_default_headers( array(
		'wheel' => array(
			'url'           => get_stylesheet_directory_uri().'/images/bg.jpg',
			'thumbnail_url' => get_stylesheet_directory_uri().'/images/bg.jpg',
			'description'   => __( 'Header', 'responsiveboat' )
		)
	) );
}
add_action('after_setup_theme', 'responsiveboat_setup_fix');


function responsive_boat_style_fix() {

	$custom_css = "
                .testimonial .section-header .white-text{
                        color: #404040;
                }
                .big-title-container .btn.red-btn, .big-title-container .btn.green-btn {
				    background: rgba(255, 255, 255, 0.15);
				}";
	wp_add_inline_style( 'responsiveboat-style', $custom_css );
}
add_action( 'wp_enqueue_scripts', 'responsive_boat_style_fix' );
`

**Comment by UVLabs** [comment]
@cristian-ungureanu wouldn't we be able to add this ourselves into the Responsive boat we offer on our website?

I know its a child theme but at least new downloaders would not have this problem

**Comment by cristian-ungureanu** [comment]
@UVLabs  We can do that but I understood that we recommend our users to take a child theme and modify it. If we update this and the users update it, we will overwrite their changes.

**Comment by UVLabs** [comment]
@cristian-ungureanu @rodica-andronache I was talking about a none backwards compatible Responsive boat.

Is there a way to update the new code of responsive boat but **NOT make it backwards compatible** so only new downloaders get the fix, and everyone who had the childtheme before would not see any update and we would just provide them with that code if they ever come to us.

I know its a child theme and they are never meant to be updated by the theme devs or else user loses changes, what im saying is can we release the fix but make it not backwards compatible or something? So existing users do not see the update @HardeepAsrani

**Comment by cristian-ungureanu** [comment]
I think we can do this without changing the version. @rodica-andronache what do you think?

**Comment by UVLabs** [comment]
@cristian-ungureanu that code didn't seem to change the menu color @rodica-andronache

**Comment by MikeSheridan82** [comment]
Hello, what file would i be adding that code to in order to make this fix work?

**Comment by HardeepAsrani** [comment]
@MikeSheridan82 functions.php file of your child theme. :)
