### ISSUE TITLE
Testimonials background color requires two clicks with Zerif PRO

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/responsive-boat#40]
https://github.com/Codeinwp/zerif-pro/issues/551

**Comment by cristian-ungureanu** [comment]
@UVLabs @rodica-andronache this seems to work fine. @UVLabs, you can try to clear the cache, maybe the client have a plugin or something like that. The js for alpha color picker is in the parent theme so it can't work there and not here,

**Comment by UVLabs** [comment]
@rodica-andronache @cristian-ungureanu seems like the recent updates might have fixed this. Closing.
