### ISSUE TITLE
update theme with fixes + notice

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/responsive-boat#42]
@rodica-andronache what do you think about updating this with latest zerif fixes + add a notice on activation/ customizer : 

" This child theme is not maintained anymore, consider using the parent theme Zerif Lite or check-out our latest free one page theme : Hestia."

On both zerif lite and hestia we should have links to their w.org previews, same can go for zblackbeard/one pirate etc.

**Comment by rodica-andronache** [comment]
@ineagu it's a good idea to maybe move those users to Hestia, and also to fix the existing issues for new users, but I'm not sure how that will go for the current users. If we break their sites, maybe they will not be very happy to try another of our themes.
I didn't understand here: "On both zerif lite and hestia we should have links to their w.org previews, same can go for zblackbeard/one pirate etc." you mean the links in the message  This child theme is not maintained anymore, consider using the parent theme Zerif Lite or check-out our latest free one page theme : Hestia ? 
And for zblackbeard etc, you mean to update all the child themes?

**Comment by ineagu** [comment]
Yep the links in the message.

Yep, update all old zerif child themes.

If some sites break, we should be able to provide a quick solution with a doc or so
